apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: conditions
spec:
  version: "v0.1.0"
  platforms:
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    uri: https://github.com/youngnick/conditions/releases/download/v0.1.0/conditions_linux_amd64.tar.gz
    sha256: ""
    files:
    - from: "./conditions"
      to: "."
    - from: LICENSE
      to: "."
    bin: "conditions"
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    uri: https://github.com/youngnick/conditions/releases/download/v0.1.0/conditions_darwin_amd64.tar.gz
    sha256: ""
    files:
    - from: "./conditions"
      to: "."
    - from: LICENSE
      to: "."
    bin: "conditions"
  - selector:
      matchLabels:
        os: windows
        arch: amd64
    uri: https://github.com/youngnick/conditions/releases/download/v0.1.0/conditions_windows_amd64.zip
    sha256: ""
    files:
    - from: "/conditions.exe"
      to: "."
    - from: LICENSE
      to: "."
    bin: "conditions.exe"
  shortDescription: A new plugin
  homepage: https://github.com/youngnick/conditions
  caveats: |
    Usage:
      $ kubectl conditions

    For additional options:
      $ kubectl conditions --help
      or https://github.com/youngnick/conditions/blob/v0.1.0/doc/USAGE.md

  description: |
    This is a new plugin
